### ISSUE TITLE
Which license applies to openexr-wrap-em?

### ISSUE THREAD

**Issue by yellowtailfan** [disneyresearch/openexr-wrap-em#1]
There is no license file in the openexr-wrap-em repo. Is it released under the [same license as JERI](https://github.com/disneyresearch/jeri/blob/master/LICENSE)?

**Comment by cbreak-black** [comment]
Yes, that is correct, this wrapper has the same license as Jeri. It is basically part of the Jeri Project, and just in a separate repository for logistical reasons.
This does not include OpenEXR, emscripten and the other external dependencies.

**Comment by yellowtailfan** [comment]
Thanks very much for your quick and helpful response!
